/*
    
    Students Portfolio Repo

    You should have already had created a Student Portfolio Repo for both Frontend and Backend.

    Your app will be improved by connecting it to a local MongoDB storage and enabling creation, read, update and deleting in a real database.

    //BACKEND

    Your previously developed backend should have the following routes included:

    GET /students => returns the list of students
    GET /students/:id => returns a single student
    POST /students => create a new student
    PUT /students/:id => edit the student with the given id
    DELETE /students/:id => delete the student with the given id

    [EXTRA] POST /checkEmail => check if another student has the same email. The parameter should be passed in the body
    It should not be possible to add a new student if another has the same email.

    Student:
    
    - _id --> Autogenerated from mongo
    - name
    - surname
    - email
    - dateOfBirth

    You have to refactor previous APIs, so new APIs will be the following:
    
    GET /students => returns the list of students, shall NOT return projects
    GET /students/:id => returns a single student
    POST /students => create a new student
    PUT /students/:id => edit the student with the given id
    DELETE /students/:id => delete the student with the given id

    //FRONTEND

    You should have the following features in your frontend:

    - Add a new Student ([EXTRA]use CheckEmail before sending the post to the backend)
    - Show Students on a list, with query by Country
    - Every Student could be edited or deleted
*/
 